heat_template_version: 2013-05-23

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
    default: ubuntuCloud14
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: my_key1
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach server to.
    default: my_net1
  public_network:
    type: string
    label: Public network name or ID
    description: Network to attach server to.
    default: admin_floating_net

resources:
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: Security_group
      rules:
        - port_range_min: 1
          port_range_max: 65535
          protocol: tcp
          direction: ingress
        - port_range_min: 1
          port_range_max: 65535
          protocol: tcp
          direction: egress
        - port_range_min: 22
          port_range_max: 22
          protocol: tcp
          direction: ingress
        - port_range_min: 22
          port_range_max: 22
          protocol: tcp
          direction: egress
        - port_range_min: 80
          port_range_max: 80
          protocol: tcp
          direction: ingress
        - port_range_min: 80
          port_range_max: 80
          protocol: tcp
          direction: egress
        - protocol: icmp
          direction: egress
        - protocol: icmp
          direction: ingress

  instance1:
    type: instance1.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: private_network }
      public_network: { get_param: public_network }
      instance2_ip: { get_attr: [instance2, ip] }
      instance3_ip: { get_attr: [instance3, ip] }
      security_group: { get_resource: security_group }

  instance2:
    type: instance2.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: private_network }
      public_network: { get_param: public_network }
      instance3_ip: { get_attr: [instance3, ip] }
      security_group: { get_resource: security_group }

  instance3:
    type: instance3.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: private_network }
      public_network: { get_param: public_network }
      security_group: { get_resource: security_group }

  instance4:
    type: instance4.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: private_network }
      public_network: { get_param: public_network }
      instance1_ip: { get_attr: [instance1, ip] }
      security_group: { get_resource: security_group }

